# Site settings
title: MUSA
email: musa@math.berkeley.edu
url:   https://musa.berkeley.edu
baseurl: /~mahrud/musa/_site
description: >
  We are the Mathematics Undergraduate Student Association
  at the University of California, Berkeley.
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MUSA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/musa.berkeley/

# Team names, titles and social links
people:
- name:     Irra Na 
  position:     Professional Chair      
  pic:  Irra_Na.jpg     
       
- name:         Ryan Shaw       
  position:     Professional Chair      
  pic:  Ryan_Shaw.jpg   
       
- name:         Ruta Jawale     
  position:     Publicity Chair 
  pic:  Ruta_Jawale.jpg 
       
- name:         Cynthia Shen    
  position:     Publicity Chair 
  pic:  Cynthia_Shen.jpg        
       
- name:         Victor Hakim    
  position:     Social Chair    
  pic:  Victor_Hakim.jpg        
       
- name:         Mahnoor Mian    
  position:     Social Chair    
  pic:  Mahnoor_Mian.jpg        
       
- name:         Edgar Rodriguez 
  position:     Outreach Chair  
  pic:  Edgar_Rodriguez.jpg     
       
- name:         Anna Leskova    
  position:     Outreach Chair  
  pic:  Anna_Leskova.jpg        
       
- name:         Jerry Wu        
  position:     Academic Chair  
  pic:  Jerry_Wu.jpg    
       
- name:         Brandon Van Over        
  position:     Academic Chair  
  pic:  Brandon_Van_Over.jpg    
       
- name:         Brian Burks     
  position:     Academic Chair  
  pic:  Brian_Burks.jpg 
       
- name:         Michelle Ko     
  position:     Treasurer       
  pic:  Michelle_Ko.jpg 
       
- name:         Mahrud Sayrafi  
  position:     Webmaster       
  pic:  Mahrud_Sayrafi.jpg      
       
- name:         Clark Lyons     
  position:     Vice President  
  pic:  Clark_Lyons.jpg 
       
- name:         Cailan Li       
  position:     President       
  pic:  Cailan_Li.jpg   

spotlights:
- name: Pauline Sperry
  title: First Female Assistant and Associate Professor at UC Berkeley.</p>
  desc: "2017 marks the centennial of the addition of the first woman to become an associate professor in the Berkeley Math Department – Pauline Sperry. Born in 1885 in Massachusetts, she studied math and music in Smith College, where she later returned for graduate work and teaching mathematics. She continued her graduate studies in University of Chicago, where she completed her dissertation in projective differential geometry and in 1916 was awarded a doctorate. Then in 1917, a hundred years ago, she joined UC Berkeley as an instructor, promoted to assistant professor in 1923 and eventually to associate professor in 1932, both demonstrating her brilliance in advanced mathematics as the first woman to achieve those positions in Berkeley. By 1950, she had advised five Ph.D. candidates, published a bibliography and two textbooks, and mentored many women in her decades of service to the Berkeley Math Department.
Sperry’s distinguished career came to a premature end in 1950 when she was dismissed for refusing to sign an oath of loyalty at the height of the anti-communist era. She believed as a matter of principle that the oath would encroach on political freedom. After 2 years, the court ruled in her and other non-signer’s favor, but as she was already passed the retirement age, she was reinstated as associate professor emerita. Later, the University President Robert G. Sproul praised her “exceptional ability as a teacher in a subject in which the quality of teaching can be responsible in large measure for the difference between brilliance and mediocrity in a student's work.”
After retiring from teaching, Sperry dedicated her time to promote human rights through involvement in the American Civil Liberties Union, the League of Women Voters, and the Committee for a Sane Nuclear Policy. A remarkable philanthropist, she also gave to help those in need, claiming that to be happy, one should be “bold enough to ask the right questions, and brave enough to face the answers about the untouchable subject, money. ... Give 'till it hurts!”."
  pic: sperry.jpg


# Build settings
markdown: kramdown
permalink: pretty
