####### SITEWISE CONFIGURATION #########
# Site settings
title: MUSA
email: musa@math.berkeley.edu
url:   https://musa.berkeley.edu
baseurl: ""
description: >
  We are the Mathematics Undergraduate Student Association
  at the University of California, Berkeley.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MUSA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/musa.berkeley/




### EDIT THIS ###################
# Math Mondays
current_monday:
- title:    Infinite Ramsey theory
  speaker:  Sung Hyup Lee
  date:     5 February, 2018
  room:     939 Evans
  abstract: To be announced.

monday:
- title:    Infinite games
  speaker:  John R. Steel
  date:     29 January, 2018
  room:     1015 Evans
  abstract: We consider games of the following sort. There are two players, I and II, and a payoff set $A$. The players alternate making moves, and at the end of the game have produced an infinite sequence s of moves. Player I wins if and only if $s$ is in $A$. This game is called $G_A$, and it is said to be determined if one of the two players has a winning strategy.</p><p>For which $A$ is $G_A$ determined? The question turns out to be a basic one in the foundations of mathematics. Its answer is intimately connected to the existence of infinities much larger than the countable infinity involved in the description of the game.</p><p>We shall explain this connection further, in a non-technical talk aimed at a general audience.


# Featured Problems
current_problem:
- title: Homeomorphism classes in <b>R</b><sup>n</sup>
  problem: We say that two subsets, X and Y, of <b>R</b><sup>n</sup> are <i>homeomorphic</i> if there is a continuous bijection from X to Y whose inverse is also continuous.</p><p>Show that there exist two subsets of <b>R</b><sup>n</sup> which are not homeomorphic, but do have continuous bijections between them.
  prereq: Math 104

problems:


# Team names, titles and social links
people:
- lname:     Ryan Shaw
  lposition: President
  lpic:      Ryan_Shaw.png
  rname:     Ning McKenzie
  rposition: Vice President
  rpic:      Ning_McKenzie.jpg

- lname:     Cailan Li
  lposition: Treasurer, President Emeritus
  lpic:      Cailan_Li.jpg
  rname:     Clark Lyons
  rposition: Pi-E Day Officer, Vice President Emeritus
  rpic:      Clark_Lyons.jpg

- lname:     Sung Hyup Lee
  lposition: Academic Chair
  lpic:      Sung_Hyup_Lee.jpg
  rname:     Yu Ma
  rposition: Academic Chair
  rpic:      Yu_Ma.jpg

- lname:     Aidan Backus
  lposition: Outreach Chair, Webmaster
  lpic:      Aidan_Backus.jpg
  rname:     Joshua Lin
  rposition: Outreach Chair
  rpic:      Joshua_Lin.jpg

- lname:     Mahnoor Mian
  lposition: Social Chair
  lpic:      Mahnoor_Mian.jpg
  rname:     Sanat Mulay
  rposition: Social Chair
  rpic:      Sanat_Mulay.png

- lname:     Lakshmi Ramesh
  lposition: Outreach Chair, BUMP Head Mentor
  lpic:      Lakshmi_Ramesh.jpg
  rname:     Margo Oka
  rposition: Social Chair
  rpic:      Margo_Oka.jpg

- lname:     Cynthia Shen
  lposition: Publicity Chair
  lpic:      Cynthia_Shen.jpg
  rname:     Edgar Rodriguez
  rposition: Publicity Chair
  rpic:      Edgar_Rodriguez.jpg


food:
- name: Hoodie, gray or blue
  price: $30

- name: T-shirt, gray or blue
  price: $15

- name: Tamales, chicken or pork
  price: $1.25

- name: Burrito, steak and cheese
  price: $1.00

- name: Burrito, bean and cheese
  price: $2.00

- name: Cup noodles
  price: $0.50

- name: Soda
  price: $0.75

- name: Muffin
  price: $1.00

- name: Trail mix
  price: $0.75

- name: Mandarin (seasonal)
  price: $0.25

- name: Apple (seasonal)
  price: $0.50

- name: Banana (seasonal)
  price: $0.50

- name: Chips
  price: $0.50

- name: Fruit by the Foot
  price: $0.50

- name: Snickers bar
  price: $1.00

- name: Ice cream bar
  price: $1.25

hours:
- time: 10 AM
  monday: Lakshmi Ramesh
  tuesday: Mahnoor Mian
  wednesday: Lakshmi Ramesh
  thursday: Joshua Lin
  friday: Margo Oka

- time: 11 AM
  monday: Aidan Backus
  tuesday: Mahnoor Mian
  wednesday: Aidan Backus
  thursday: Yu Ma
  friday: Sung Hyup Lee

- time: 12 PM
  monday: Cynthia Shen
  tuesday: Ning McKenzie
  wednesday: Ning McKenzie
  thursday: Yu Ma
  friday: Sung Hyup Lee

- time: 1 PM
  monday: Cynthia Shen
  tuesday: Ryan Shaw
  wednesday: Joshua Lin
  thursday: Ryan Shaw
  friday: Edgar Rodriguez

- time: 2 PM
  monday: Margo Oka
  tuesday: Ryan Shaw
  wednesday: Cailan Li
  thursday: Ning McKenzie
  friday: Edgar Rodriguez

- time: 3 PM
  monday: Cailan Li
  tuesday: Sanat Mulay
  wednesday: Clark Lyons
  thursday: Sanat Mulay
  friday: Cailan Li








########### OLD DATA
mondayF2017:
- title:    Homology theories and their applications
  speaker:  Kat Christianson
  date:     16 October, 2017 at 6 PM
  room:     740 Evans
  abstract: Homology is a powerful algebraic tool that arises naturally in a wide range of different areas of modern mathematics. The main goal of this talk is to provide an introduction to how homology theories are defined and how they are used in practice. We will focus on two standard homology theories in algebraic topology as examples. After laying some theoretical foundations for these two homology theories, we will consider a couple applications of those foundations to questions in geometry and commutative algebra.
- title:    The Fibonacci Sequence modulo p &mdash; Around and around we go
  speaker:  Alexander Youcis
  date:     9 October, 2017
  room:     740 Evans
  abstract: The Fibonacci sequence has, in the past decade or so, taken on an almost meme like quality. That being said, it is an interesting sequence of integers, the structure of which can get surprisingly complex. We will be interested in this talk in what sort of periodicity properties the Fibonacci sequence has. Of course, this can’t be the normal notion of periodicity (since the Fibonacci sequence is increasing). Instead, we mean the periodicity of the sequence modulo a prime p. It turns out that the study of such a problem naturally leads one to consider slightly more sophisticated problems in number theory and algebra.

- title:    Sharks in the Shallows
  speaker:  Sri Kunnawalkam Elayvalli
  date:     25 September, 2017
  room:     740 Evans
  abstract: I will talk about problems in mathematics that are so easy to state that even your grandmother can understand them, but are so difficult to solve that no one ever in history has solved them. The interesting thing about the problems I will present is that they are not very famous in the public eye (unlike the twin prime conjecure, Goldbach's conjecture, the abc conjecture, and so on). The platter will include problems of various different flavors, like numbers, sets, triangles, points, sums, etc.

- title:    To Infinity and Beyond &mdash; The strange world of ordinal arithmetic
  speaker:  Professor Richard E. Borcherds
  date:     11 September, 2017
  room:     740 Evans
  abstract: Beyond the usual numbers 0, 1, 2, 3, ..., lie Cantor's countable ordinal numbers ω, ω+1, ..., ω+ω, ..., ε<sub>0</sub>, .... In some way their arithmetic is similar to the natural numbers; one can add, multiply and raise them to powers and define primes and so on. However in other ways their arithmetic looks a little strange; for example, 1+ω < ω+1.

monday2016:
- title: Eigenvectors of Tensors
  speaker: Bernd Sturmfels
  date: 12 September, 2016
  abstract: Eigenvectors of square matrices are central to linear algebra. Eigenvectors of tensors are a natural generalization. The spectral theory of tensors was pioneered about a decade ago, and has since found numerous applications, but it is also intimately connected to classical questions in optimization and dynamics. We present an introduction to this theory.

- title: Cutout Instructions and Geometric Invariants
  speaker: Julian Chaidez
  date: 19 September, 2016
  abstract: Suppose that you are given paper cutout instructions for a very large looking polyhedron, with many sides. How could you distinguish between a real set of instructions, which describes a polyhedron that can actually be constructed, and fake set of instructions, which appears valid at a glance but actually described an unbuildable shape?

- title: The Global Attractor Conjecture
  speaker: Christopher Eur
  date: 26 September, 2016
  abstract: The Global Attractor Conjecture (GAC) is a fundamental conjecture in chemical reaction network theory (CRNT) that has eluded proofs for decades despite appearing intuitively obvious. In this talk, we introduce CRNT following works of Jackson, Horn, and Feinberg, and discuss its ties to algebraic geometry and convex geometry. We conclude with a sketch of the recently proposed proof of GAC.

- title: Where to find Galois representations, and why
  speaker: Sander Mack-Crane
  date: 3 October, 2016
  abstract: Starting from prime numbers, we'll discuss one of the motivating problems in number theory, and how it connects to Galois theory and then to Galois representations. This sets us up for a gentle overview of what the Langlands program is all about. As an example we'll discuss the simplest case, known as class field theory. Knowledge of abstract algebra will be helpful.

- title: The p-Group Fixed Point Theorem
  speaker: Qiaochu Yuan
  date: 10 October, 2016
  abstract: In this talk, we'll describe a surprisingly useful result from group theory that can be applied to prove many of the basic results in elementary number theory. We'll start with Fermat's little theorem and Wilson's theorem and work our way up from there. Time permitting we may make it all the way up to quadratic reciprocity.

- title: Differential Equations in Algebraic Geometry
  speaker: Martin Olsson
  date: 17 October, 2016
  abstract: I will discuss some of the algebraic aspects of ordinary linear differential equations. While the theory of such equations, as presented for example in math 1B, is analytic in nature involving things like the derivative and limits, one can, in fact, study such equations more algebraically over the rationals, or even finite fields.

- title: From Linear Maps to Multilinear Maps Through Cryptography
  speaker: Mahrud Sayrafi
  date: 24 October, 2016
  abstract: In this talk we will see how almost all aspects of cryptography essentially boil down to studying functions that are easy to compute but hard to invert without some extra information. While analyzing these functions often involves tools from statistics or computer science, the problems at the core are mathematical in nature, and in fact, you have known all of them since precalc.

- title: Classical and Quantum Chaos
  speaker: Maciej Zworski
  date: 31 October, 2016
  abstract: Classical chaos was famously described by Edward Lorenz (of butterfly effect fame) as the situation when the present determines the future, but the approximate present does not approximately determine the future. I will illustrate that by some example and also, for contrast, show completely integrable systems (that is, predictable systems).

- title: Invariants of nonunique factorization
  speaker: Christopher O'Neill
  date: 7 November, 2016
  abstract: The fundamental theorem of arithmetic states that every integer factors uniquely as a product of primes. Non-unique factorization theory examines settings where uniqueness of factorization fails to hold (that is, settings in which every element can be factored, but possibly in more than one way). This relatively new field has many algebraic and combinatorial aspects.

- title: The calculus of variations and weak KAM theory
  speaker: Craig Evans
  date: 14 November, 2016
  abstract: I will first discuss the Newtonian, the Lagrangian and the Hamiltonian interpretations for the dynamics of a particle moving in a conservative field of forces, and explain how to extract interesting information such as conservation laws and the Virial Theorem. I will then generalize to weak KAM (= Kolmogorov, Arnold, Moser) theory.

- title: Supersymmetry in algebra and geometry
  speaker: Vera Serganova
  date: 28 November, 2016
  abstract: I will give a brief introduction to superalgebras and illustrate on examples how they appear in different areas of mathematics. My examples will include the proof of Amitzur-Levitski identity, the duality between orthogonal and symplectic groups and de Rham complex. We will also discuss the notion of supertrace.

- title: An Introduction to Analytic Number Theory
  speaker: Cailan Li
  date: 30 January, 2017
  abstract: In this talk we will first give a crash course in complex analysis and then talk about the beautiful Riemann zeta function and its generalization. We will then talk about the shiny objects known as modular forms, and some of their applications. In particular, we will discuss the role modular forms played in Andrew Wiles' proof of Fermat's Last Theorem.

- title: Local fields and the geometry of the p-adics
  speaker: Alex Carney
  date: 6 February, 2017
  abstract: Local fields are a formalization of the idea that often in number theory, problems are easier to solve mod p than over the integers or the rationals. We'll start by defining the p-adics, the most common example of a local field, and describe some of their strange and interesting properties. At the end, I will briefly point to some exciting modern directions in the study of local fields.

- title: Reflection groups, wallpaper groups, and orbifolds
  speaker: Richard Borcherds
  date: 13 February, 2017
  abstract: This talk will describe how to classify things like the 18 archimedean solids and the 17 wallpaper groups using orbifolds.

- title: Helpful ways to visualize spaces
  speaker: Jeff Hicks
  date: 27 February, 2017
  abstract: A lot of my intuition for mathematics comes from drawing pictures of the problem I want to solve. As a topologist, this means trying to come up with clean visual representations of various topological spaces. A good drawing for a space should ideally be mathematically motivated and intuitive.

- title: 4-manifolds revisited
  speaker: Peter Teichner
  date: 20 March, 2017
  abstract: I'll give a classification of manifolds up to dimension 4.

- title: Quantum sets
  speaker: Mariusz Wodzicki
  date: 10 April, 2017
  abstract: A set is generally considered to be the simplest structure of Mathematics. Every set comes disguised under a number of other structures, however. While exploring some of them, we shall encounter what I propose to call a quantum set, in analogy to quantum groups.

retired:
- lname:     Irra Na
  lposition: Professional Chair
  lpic:      Irra_Na.jpg
  rname:     Ruta Jawale
  rposition: Publicity Chair
  rpic:      Ruta_Jawale.jpg
- lname:     Victor Hakim
  lposition: Social Chair
  lpic:      Victor_Hakim.jpg
  rname:     Anna Leskova
  rposition: Outreach Chair
  rpic:      Anna_Leskova.jpg
- lname:     Brandon Van Over
  lposition: Academic Chair
  lpic:      Brandon_Van_Over.jpg
  rname:     Mahrud Sayrafi
  rposition: President
  remail:    mahrud@berkeley.edu
  rpic:      Mahrud_Sayrafi.jpg
- lname:     Michelle Ko
  lposition: Treasurer
  lpic:      Michelle_Ko.jpg
  rname:     Jerry Wu
  rposition: Academic Chair
  rpic:      Jerry_Wu.jpg
- lname:     Brian Burks
  lposition: Recreational Math
  lpic:      Brian_Burks.jpg
  rname:
  rposition:
  rpic:      filler.png


spotlights:
- name: Pauline Sperry
  title: First Female Assistant and Associate Professor at UC Berkeley.</p>
  desc: "2017 marks the centennial of the addition of the first woman to become an associate professor in the Berkeley Math Department – Pauline Sperry. Born in 1885 in Massachusetts, she studied math and music in Smith College, where she later returned for graduate work and teaching mathematics. She continued her graduate studies in University of Chicago, where she completed her dissertation in projective differential geometry and in 1916 was awarded a doctorate. Then in 1917, a hundred years ago, she joined UC Berkeley as an instructor, promoted to assistant professor in 1923 and eventually to associate professor in 1932, both demonstrating her brilliance in advanced mathematics as the first woman to achieve those positions in Berkeley. By 1950, she had advised five Ph.D. candidates, published a bibliography and two textbooks, and mentored many women in her decades of service to the Berkeley Math Department.
Sperry’s distinguished career came to a premature end in 1950 when she was dismissed for refusing to sign an oath of loyalty at the height of the anti-communist era. She believed as a matter of principle that the oath would encroach on political freedom. After 2 years, the court ruled in her and other non-signer’s favor, but as she was already passed the retirement age, she was reinstated as associate professor emerita. Later, the University President Robert G. Sproul praised her “exceptional ability as a teacher in a subject in which the quality of teaching can be responsible in large measure for the difference between brilliance and mediocrity in a student's work.”
After retiring from teaching, Sperry dedicated her time to promote human rights through involvement in the American Civil Liberties Union, the League of Women Voters, and the Committee for a Sane Nuclear Policy. A remarkable philanthropist, she also gave to help those in need, claiming that to be happy, one should be “bold enough to ask the right questions, and brave enough to face the answers about the untouchable subject, money. ... Give 'till it hurts!”."
  pic:      sperry.jpg

# Build settings
markdown: kramdown
permalink: pretty
