####### SITEWISE CONFIGURATION #########
# Site settings
title: MUSA
email: musa@math.berkeley.edu
url:   https://musa.berkeley.edu
baseurl: ""
description: >
  We are the Mathematics Undergraduate Student Association
  at the University of California, Berkeley.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MUSA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/musa.berkeley/




### EDIT THIS ###################
# Events
events:
- name:        LaTeX Workshop
  location:    1015 Evans
  date:        1 February, 2018 at 6 PM
  description: Tired of receiving partial credit because your graders couldn't read your handwriting? We'll be holding a LaTeX workshop! LaTeX is a typesetting language that is very useful if you want to create clean professional notes and homework assignments, or create beautiful diagrams. We will give a crash course into LaTeX, and will have experts at the event to answer your questions and help you one on one.

- name:        E Day Party!
  location:    ???
  date:        7 February, 2018
  description: To be announced...

- name:        SURF and REU research workshop
  location:    1015 Evans
  date:        8 February, 2018 at 5 PM
  description: To be announced...

- name:        Marriages and Matchings
  location:    1015 Evans
  date:        15 February, 2018 at 6 PM
  description: To be announced...



# Math Mondays
monday:
- title:    Infinite games
  speaker:  John R. Steel
  date:     29 January, 2018
  room:     1015 Evans
  abstract: We consider games of the following sort. There are two players, I and II, and a payoff set $A$. The players alternate making moves, and at the end of the game have produced an infinite sequence s of moves. Player I wins if and only if $s$ is in $A$. This game is called $G_A$, and it is said to be determined if one of the two players has a winning strategy.</p><p>For which $A$ is $G_A$ determined? The question turns out to be a basic one in the foundations of mathematics. Its answer is intimately connected to the existence of infinities much larger than the countable infinity involved in the description of the game.</p><p>We shall explain this connection further, in a non-technical talk aimed at a general audience. 



# Team names, titles and social links
people:
- lname:     Ryan Shaw
  lposition: President
  lpic:      Ryan_Shaw.jpg
  rname:     Ning McKenzie
  rposition: Vice President
  rpic:      Ning_McKenzie.jpg

- lname:     Cailan Li
  lposition: Treasurer, President Emeritus
  lpic:      Cailan_Li.jpg
  rname:     Clark Lyons
  rposition: Pi-E Day Officer, Vice President Emeritus
  rpic:      Clark_Lyons.jpg

- lname:     Sung Hyup Lee
  lposition: Academic Chair
  lpic:      Sung_Hyup_Lee.jpg
  rname:     Yu Ma
  rposition: Academic Chair
  rpic:      Yu_Ma.jpg

- lname:     Aidan Backus
  lposition: Outreach Chair, Webmaster
  lpic:      Aidan_Backus.jpg
  rname:     Joshua Lin
  rposition: Outreach Chair
  rpic:      Joshua_Lin.jpg

- lname:     Mahnoor Mian
  lposition: Social Chair
  lpic:      Mahnoor_Mian.jpg
  rname:     Sanat Mulay
  rposition: Social Chair
  rpic:      Sanat_Mulay.jpg

- lname:     Lakshmi Ramesh
  lposition: Outreach Chair, BUMP Head Mentor
  lpic:      Lakshmi_Ramesh.jpg
- rname:     Margo Oka
  rposition: Social Chair
  rpic:      Margo_Oka.jpg

- lname:     Cynthia Shen
  lposition: Publicity Chair
  lpic:      Cynthia_Shen.jpg
  rname:     Edgar Rodriguez
  rposition: Publicity Chair
  rpic:      Edgar_Rodriguez.jpg


food:
- lname: Hoodie
  lpic: Hoodie.jpg
  lprice: $30.00
  rname: T-Shirt
  rpic: TShirt.jpg
  rprice: $15.00

- lname: Ice cream sandwich
  lpic: IceCreamSandwich.jpg
  lprice: $1.00
  rname: Soda
  rpic: Soda.jpg
  rprice: $0.75

- lname: Muffin
  lpic: Muffin.jpg
  lprice: $1.00
  rname: Cup noodles
  rpic: Snacks.jpg
  rprice: $0.50

- lname: Trail mix
  lprice: $0.75
  lpic: Snacks.jpg
  rname: Chips
  rpic: Chips.jpg
  rprice: $0.50

  lname: Orange
  lpic: Fruit.jpg
  lprice: $0.25
  rname: Banana
  rpic: Fruit.jpg
  rprice: $0.50


hours:
- time: 10 AM
  monday: Margo Oka
  tuesday: Mahnoor Mian
  wednesday: Sanat Mulay
  thursday: Joshua Lin
  friday: Margo Oka

- time: 11 AM
  monday: Aidan Backus
  tuesday: Mahnoor Mian
  wednesday: Yu Ma
  thursday: Aidan Backus
  friday: Sung Hyup Lee

- time: 12 PM
  monday: Cynthia Shen
  tuesday: Ning McKenzie
  wednesday: Joshua Lin
  thursday: Yu Ma
  friday: Sung Hyup Lee

- time: 1 PM
  monday: Cynthia Shen
  tuesday: Ryan Shaw
  wednesday: Ning McKenzie
  thursday: Ryan Shaw
  friday: Edgar Rodriguez

- time: 2 PM
  monday: Edgar Rodriguez
  tuesday: Ryan Shaw
  wednesday: Clark Lyons
  thursday: Ning McKenzie
  friday: Clark Lyons

- time: 3 PM
  monday: Cailan Li
  tuesday: Sanat Mulay
  wednesday: Clark Lyons
  thursday: Sanat Mulay
  friday: Cailan Li








########### OLD DATA
mondayF2017:
- title:    Homology theories and their applications
  speaker:  Kat Christianson
  date:     16 October, 2017 at 6 PM
  room:     740 Evans
  abstract: Homology is a powerful algebraic tool that arises naturally in a wide range of different areas of modern mathematics. The main goal of this talk is to provide an introduction to how homology theories are defined and how they are used in practice. We will focus on two standard homology theories in algebraic topology as examples. After laying some theoretical foundations for these two homology theories, we will consider a couple applications of those foundations to questions in geometry and commutative algebra.
- title:    The Fibonacci Sequence modulo p &mdash; Around and around we go
  speaker:  Alexander Youcis
  date:     9 October, 2017
  room:     740 Evans
  abstract: The Fibonacci sequence has, in the past decade or so, taken on an almost meme like quality. That being said, it is an interesting sequence of integers, the structure of which can get surprisingly complex. We will be interested in this talk in what sort of periodicity properties the Fibonacci sequence has. Of course, this can’t be the normal notion of periodicity (since the Fibonacci sequence is increasing). Instead, we mean the periodicity of the sequence modulo a prime p. It turns out that the study of such a problem naturally leads one to consider slightly more sophisticated problems in number theory and algebra.

- title:    Sharks in the Shallows
  speaker:  Sri Kunnawalkam Elayvalli
  date:     25 September, 2017
  room:     740 Evans
  abstract: I will talk about problems in mathematics that are so easy to state that even your grandmother can understand them, but are so difficult to solve that no one ever in history has solved them. The interesting thing about the problems I will present is that they are not very famous in the public eye (unlike the twin prime conjecure, Goldbach's conjecture, the abc conjecture, and so on). The platter will include problems of various different flavors, like numbers, sets, triangles, points, sums, etc.

- title:    To Infinity and Beyond &mdash; The strange world of ordinal arithmetic
  speaker:  Professor Richard E. Borcherds
  date:     11 September, 2017
  room:     740 Evans
  abstract: Beyond the usual numbers 0, 1, 2, 3, ..., lie Cantor's countable ordinal numbers ω, ω+1, ..., ω+ω, ..., ε<sub>0</sub>, .... In some way their arithmetic is similar to the natural numbers; one can add, multiply and raise them to powers and define primes and so on. However in other ways their arithmetic looks a little strange; for example, 1+ω < ω+1.

retired:
- name:     Irra Na
  position: Professional Chair
  pic:      Irra_Na.jpg

- name:     Ruta Jawale
  position: Publicity Chair
  pic:      Ruta_Jawale.jpg

- name:     Victor Hakim
  position: Social Chair
  pic:      Victor_Hakim.jpg

- name:     Anna Leskova
  position: Outreach Chair
  pic:      Anna_Leskova.jpg

- name:     Brandon Van Over
  position: Academic Chair
  pic:      Brandon_Van_Over.jpg

- name:     Mahrud Sayrafi
  position: President
  email:    mahrud@berkeley.edu
  pic:      Mahrud_Sayrafi.jpg

- name:     Michelle Ko
  position: Treasurer
  pic:      Michelle_Ko.jpg

- name:     Jerry Wu
  position: Academic Chair
  pic:      Jerry_Wu.jpg

- name:     Brian Burks
  position: Recreational Math
  pic:      Brian_Burks.jpg


spotlights:
- name: Pauline Sperry
  title: First Female Assistant and Associate Professor at UC Berkeley.</p>
  desc: "2017 marks the centennial of the addition of the first woman to become an associate professor in the Berkeley Math Department – Pauline Sperry. Born in 1885 in Massachusetts, she studied math and music in Smith College, where she later returned for graduate work and teaching mathematics. She continued her graduate studies in University of Chicago, where she completed her dissertation in projective differential geometry and in 1916 was awarded a doctorate. Then in 1917, a hundred years ago, she joined UC Berkeley as an instructor, promoted to assistant professor in 1923 and eventually to associate professor in 1932, both demonstrating her brilliance in advanced mathematics as the first woman to achieve those positions in Berkeley. By 1950, she had advised five Ph.D. candidates, published a bibliography and two textbooks, and mentored many women in her decades of service to the Berkeley Math Department.
Sperry’s distinguished career came to a premature end in 1950 when she was dismissed for refusing to sign an oath of loyalty at the height of the anti-communist era. She believed as a matter of principle that the oath would encroach on political freedom. After 2 years, the court ruled in her and other non-signer’s favor, but as she was already passed the retirement age, she was reinstated as associate professor emerita. Later, the University President Robert G. Sproul praised her “exceptional ability as a teacher in a subject in which the quality of teaching can be responsible in large measure for the difference between brilliance and mediocrity in a student's work.”
After retiring from teaching, Sperry dedicated her time to promote human rights through involvement in the American Civil Liberties Union, the League of Women Voters, and the Committee for a Sane Nuclear Policy. A remarkable philanthropist, she also gave to help those in need, claiming that to be happy, one should be “bold enough to ask the right questions, and brave enough to face the answers about the untouchable subject, money. ... Give 'till it hurts!”."
  pic:      sperry.jpg

# Build settings
markdown: kramdown
permalink: pretty
