# Site settings
title: MUSA
email: musa@math.berkeley.edu
url:   https://musa.berkeley.edu
baseurl: ""
description: >
  We are the Mathematics Undergraduate Student Association
  at the University of California, Berkeley.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: MUSA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/musa.berkeley/

# Team names, titles and social links
people:
- name:     Cailan Li
  position: President
  pic:      Cailan_Li.jpg

- name:     Clark Lyons
  position: Vice President
  pic:      Clark_Lyons.jpg

- name:     Michelle Ko
  position: Treasurer
  pic:      Michelle_Ko.jpg

- name:     Jerry Wu
  position: Academic Chair
  pic:      Jerry_Wu.jpg

- name:     Sung Hyup Lee
  position: Academic Chair
  pic:      Sung_Hyup_Lee.jpg

- name:     Yu Ma
  position: Academic Chair
  pic:      Yu_Ma.jpg

- name:     Aidan Backus
  position: Outreach Chair
  pic:      Aidan_Backus.jpg

- name:     Ning McKenzie
  position: Outreach Chair
  pic:      Ning_McKenzie.jpg

- name:     Margo Oka
  position: Professional Chair
  pic:      Margo_Oka.jpg

- name:     Ryan Shaw
  position: Professional Chair
  pic:      Ryan_Shaw.jpg

- name:     Cynthia Shen
  position: Publicity Chair
  pic:      Cynthia_Shen.jpg

- name:     Edgar Rodriguez
  position: Publicity Chair
  pic:      Edgar_Rodriguez.jpg

- name:     Brian Burks
  position: Recreational Math
  pic:      Brian_Burks.jpg

- name:     Joshua Lin
  position: Recreational Math
  pic:      Joshua_Lin.jpg

- name:     Lakshmi Ramesh
  position: Social Chair
  pic:      Lakshmi_Ramesh.jpg

- name:     Mahnoor Mian
  position: Social Chair
  pic:      Mahnoor_Mian.jpg

- name:     Sanat Mulay
  position: Social Chair
  pic:      Sanat_Mulay.jpg

retired:
- name:     Irra Na
  position: Professional Chair
  pic:      Irra_Na.jpg

- name:     Ruta Jawale
  position: Publicity Chair
  pic:      Ruta_Jawale.jpg

- name:     Victor Hakim
  position: Social Chair
  pic:      Victor_Hakim.jpg

- name:     Anna Leskova
  position: Outreach Chair
  pic:      Anna_Leskova.jpg

- name:     Brandon Van Over
  position: Academic Chair
  pic:      Brandon_Van_Over.jpg

- name:     Mahrud Sayrafi
  position: President
  email:    mahrud@berkeley.edu
  pic:      Mahrud_Sayrafi.jpg

monday:
- title:    Sharks in the Shallows
  speaker:  Sri Kunnawalkam Elayvalli
  date:     25 September, 2017
  room:     740 Evans
  abstract: I will talk about problems in mathematics that are so easy to state that even your grandmother can understand them, but are so difficult to solve that no one ever in history has solved them. The interesting thing about the problems I will present is that they are not very famous in the public eye (unlike the twin prime conjecure, Goldbach's conjecture, the abc conjecture, and so on). The platter will include problems of various different flavors, like numbers, sets, triangles, points, sums, etc.
- title:    To Infinity and Beyond &mdash; The strange world of ordinal arithmetic
  speaker:  Professor Richard E. Borcherds
  date:     11 September, 2017
  room:     740 Evans
  abstract: Beyond the usual numbers 0, 1, 2, 3, ..., lie Cantor's countable ordinal numbers ω, ω+1, ..., ω+ω, ..., ε<sub>0</sub>, .... In some way their arithmetic is similar to the natural numbers; one can add, multiply and raise them to powers and define primes and so on. However in other ways their arithmetic looks a little strange; for example, 1+ω < ω+1.

spotlights:
- name: Pauline Sperry
  title: First Female Assistant and Associate Professor at UC Berkeley.</p>
  desc: "2017 marks the centennial of the addition of the first woman to become an associate professor in the Berkeley Math Department – Pauline Sperry. Born in 1885 in Massachusetts, she studied math and music in Smith College, where she later returned for graduate work and teaching mathematics. She continued her graduate studies in University of Chicago, where she completed her dissertation in projective differential geometry and in 1916 was awarded a doctorate. Then in 1917, a hundred years ago, she joined UC Berkeley as an instructor, promoted to assistant professor in 1923 and eventually to associate professor in 1932, both demonstrating her brilliance in advanced mathematics as the first woman to achieve those positions in Berkeley. By 1950, she had advised five Ph.D. candidates, published a bibliography and two textbooks, and mentored many women in her decades of service to the Berkeley Math Department.
Sperry’s distinguished career came to a premature end in 1950 when she was dismissed for refusing to sign an oath of loyalty at the height of the anti-communist era. She believed as a matter of principle that the oath would encroach on political freedom. After 2 years, the court ruled in her and other non-signer’s favor, but as she was already passed the retirement age, she was reinstated as associate professor emerita. Later, the University President Robert G. Sproul praised her “exceptional ability as a teacher in a subject in which the quality of teaching can be responsible in large measure for the difference between brilliance and mediocrity in a student's work.”
After retiring from teaching, Sperry dedicated her time to promote human rights through involvement in the American Civil Liberties Union, the League of Women Voters, and the Committee for a Sane Nuclear Policy. A remarkable philanthropist, she also gave to help those in need, claiming that to be happy, one should be “bold enough to ask the right questions, and brave enough to face the answers about the untouchable subject, money. ... Give 'till it hurts!”."
  pic:      sperry.jpg

hours:
- time: 10 AM
  monday: Yu Ma
  tuesday: Lakshmi Ramesh
  wednesday: Yu Ma
  thursday: Lakshmi Ramesh
  friday: Aidan Backus
- time: 11 AM
  monday: Mahnoor Mian
  tuesday: Jerry Wu
  wednesday: Mahnoor Mian
  thursday: Jerry Wu
  friday: Aidan Backus
- time: 12 PM
  monday: Sung Hyup Lee
  tuesday: Brian Burks
  wednesday: Clark Lyons
  thursday: --
  friday: Sanat Mulay
- time: 1 PM
  monday: Cynthia Shen
  tuesday: Brian Burks
  wednesday: Clark Lyons
  thursday: Ning McKenzie
  friday: Sanat Mulay
- time: 2 PM
  monday: Margo Oka
  tuesday: Ryan Shaw
  wednesday: Cailan Li
  thursday: Edgar Rodriguez
  friday: Cailan Li
- time: 3 PM
  monday: Margo Oka
  tuesday: Ryan Shaw
  wednesday: Joshua Lin
  thursday: Edgar Rodriguez
  friday: Joshua Lin
- time: 4 PM
  monday: Cynthia Shen
  tuesday: --
  wednesday: --
  thursday: Ning McKenzie
  friday: --
- time: 5 PM
  monday: --
  tuesday: --
  wednesday: --
  thursday: Sung Hyup Lee
  friday: --

food:
- name: Ice cream sandwich
  pic: IceCreamSandwich.jpg
  price: $1.00
- name: Soda
  pic: Soda.jpg
  price: $0.75
- name: Muffin
  pic: Muffin.jpg
  price: $1.00
- name: Cup noodles
  pic: Snacks.jpg
  price: $0.50
- name: Trail mix
  price: $0.75
  pic: Snacks.jpg
- name: Chips
  pic: Chips.jpg
  price: $0.50


# Build settings
markdown: kramdown
permalink: pretty
